## 1. Import necessary Libraries

In [2]:
#pip install mlxtend
import pandas as pd

## 2. Load the Dataset

In [4]:
online_retail_data=pd.read_excel("Online Retail.xlsx")
online_retail_data.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,2010-12-01 08:34:00,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,2010-12-01 08:34:00,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,2010-12-01 08:34:00,7.95,13047.0,United Kingdom

In [5]:
## 3. Data Understanding
online_retail_data.shape

(541909, 8)

In [6]:
online_retail_data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [7]:
online_retail_data.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [9]:
online_retail_data.describe(include="all")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909.0,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,25900.0,4070,4223,NaN,NaN,NaN,NaN,38
top,573585.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,1114.0,2313,2369,NaN,NaN,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570,NaN
min,NaN,NaN,NaN,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,2011-03-28 11:34:00,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,2011-07-19 17:17:00,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,2011-10-19 11:27:00,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN

In [11]:
online_retail_data["Country"].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

### I want to find out the total transactions happened in each country

In [13]:
online_retail_data["Country"].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

### Let's build BEST ASSOCIATES for Germany as it has more transactions

In [17]:
germany_data=online_retail_data[online_retail_data["Country"]=="Germany"]
germany_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1109,536527,22809,SET OF 6 T-LIGHTS SANTA,6,2010-12-01 13:04:00,2.95,12662.0,Germany
1110,536527,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,6,2010-12-01 13:04:00,2.55,12662.0,Germany
1111,536527,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,12,2010-12-01 13:04:00,0.85,12662.0,Germany
1112,536527,22242,5 HOOK HANGER MAGIC TOADSTOOL,12,2010-12-01 13:04:00,1.65,12662.0,Germany
1113,536527,22244,3 HOOK HANGER MAGIC GARDEN,12,2010-12-01 13:04:00,1.95,12662.0,Germany
...,...,...,...,...,...,...,...,...
541801,581578,22993,SET OF 4 PANTRY JELLY MOULDS,12,2011-12-09 12:16:00,1.25,12713.0,Germany
541802,581578,22907,PACK OF 20 NAPKINS PANTRY DESIGN,12,2011-12-09 12:16:00,0.85,12713.0,Germany
541803,581578,22908,PACK OF 20 NAPKINS RED APPLES,12,2011-12-09 12:16:00,0.85,12713.0,Germany
541804,581578,23215,JINGLE BELL HEART ANTIQUE SILVER,12,2011-12-09 12:16:00,2.08,12713.0,Germany
541805,581578,22736,RIBBON REEL MAKING SNOWMEN,10,2011-12-09 12:16:00,1.65,12713.0,Germany

In [18]:
germany_data.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [19]:
germany_data.describe(include="all")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,9495.0,9495,9495,9495.000000,9495,9495.000000,9495.000000,9495
unique,603.0,1671,1703,NaN,NaN,NaN,NaN,1
top,540458.0,POST,POSTAGE,NaN,NaN,NaN,NaN,Germany
freq,149.0,383,383,NaN,NaN,NaN,NaN,9495
mean,NaN,NaN,NaN,12.369458,2011-07-03 14:23:10.331753472,3.966930,12646.139336,NaN
min,NaN,NaN,NaN,-288.000000,2010-12-01 13:04:00,0.000000,12426.000000,NaN
25%,NaN,NaN,NaN,5.000000,2011-04-04 12:10:00,1.250000,12480.000000,NaN
50%,NaN,NaN,NaN,10.000000,2011-07-19 15:55:00,1.950000,12592.000000,NaN
75%,NaN,NaN,NaN,12.000000,2011-10-11 12:38:00,3.750000,12662.000000,NaN
max,NaN,NaN,NaN,600.000000,2011-12-09 12:16:00,599.500000,14335.000000,NaN
std,NaN,NaN,NaN,17.865719,NaN,16.549026,309.138487,NaN

In [20]:
germany_data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1109,536527,22809,SET OF 6 T-LIGHTS SANTA,6,2010-12-01 13:04:00,2.95,12662.0,Germany
1110,536527,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,6,2010-12-01 13:04:00,2.55,12662.0,Germany
1111,536527,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,12,2010-12-01 13:04:00,0.85,12662.0,Germany
1112,536527,22242,5 HOOK HANGER MAGIC TOADSTOOL,12,2010-12-01 13:04:00,1.65,12662.0,Germany
1113,536527,22244,3 HOOK HANGER MAGIC GARDEN,12,2010-12-01 13:04:00,1.95,12662.0,Germany

In [21]:
del germany_data["CustomerID"]

In [22]:
germany_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
1109,536527,22809,SET OF 6 T-LIGHTS SANTA,6,2010-12-01 13:04:00,2.95,Germany
1110,536527,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,6,2010-12-01 13:04:00,2.55,Germany
1111,536527,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,12,2010-12-01 13:04:00,0.85,Germany
1112,536527,22242,5 HOOK HANGER MAGIC TOADSTOOL,12,2010-12-01 13:04:00,1.65,Germany
1113,536527,22244,3 HOOK HANGER MAGIC GARDEN,12,2010-12-01 13:04:00,1.95,Germany
...,...,...,...,...,...,...,...
541801,581578,22993,SET OF 4 PANTRY JELLY MOULDS,12,2011-12-09 12:16:00,1.25,Germany
541802,581578,22907,PACK OF 20 NAPKINS PANTRY DESIGN,12,2011-12-09 12:16:00,0.85,Germany
541803,581578,22908,PACK OF 20 NAPKINS RED APPLES,12,2011-12-09 12:16:00,0.85,Germany
541804,581578,23215,JINGLE BELL HEART ANTIQUE SILVER,12,2011-12-09 12:16:00,2.08,Germany
541805,581578,22736,RIBBON REEL MAKING SNOWMEN,10,2011-12-09 12:16:00,1.65,Germany

In [29]:
# We need pivot table since apriori algorithim requires the onehot dataframe where it take 0 and 1 as the value for the features
germany_pivoted_data=pd.pivot_table(data=germany_data,values="Quantity",index="InvoiceNo",columns="Description",aggfunc = 'sum').fillna(0)
germany_pivoted_data

Description,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,...,YULETIDE IMAGES GIFT WRAP SET,ZINC HEART T-LIGHT HOLDER,ZINC STAR T-LIGHT HOLDER,ZINC BOX SIGN HOME,ZINC FOLKART SLEIGH BELLS,ZINC HEART LATTICE T-LIGHT HOLDER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC WILLIE WINKIE CANDLE STICK
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536527,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536840,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536861,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536967,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536983,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C580313,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C580714,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C580740,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C580989,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C581409,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
#sa_data= online_retail_data[online_retail_data["Country"] == "Saudi Arabia"]
#sa_data.head(20)

In [27]:
#sa_pivoted_data=pd.pivot_table(data=sa_data,values="Quantity",index="InvoiceNo",columns="Description",aggfunc = 'sum')
#sa_pivoted_data

In [32]:
# Now write a lambda funtion to update the values as 1 for the features which containing the value other than 0, so that it will be like onehot DF.
germany_pivoted_data_onehot=germany_pivoted_data.applymap(lambda x:0 if x==0 else 1)
germany_pivoted_data_onehot

C:\Users\USER\AppData\Local\Temp\ipykernel_3716\2590791816.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  germany_pivoted_data_onehot=germany_pivoted_data.applymap(lambda x:0 if x==0 else 1)

Description,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,...,YULETIDE IMAGES GIFT WRAP SET,ZINC HEART T-LIGHT HOLDER,ZINC STAR T-LIGHT HOLDER,ZINC BOX SIGN HOME,ZINC FOLKART SLEIGH BELLS,ZINC HEART LATTICE T-LIGHT HOLDER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC WILLIE WINKIE CANDLE STICK
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536527,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536840,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536861,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536967,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536983,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C580313,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C580714,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C580740,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C580989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C581409,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## 4. Data Mining

In [30]:
from mlxtend.frequent_patterns import apriori,association_rules

In [39]:
# apriori algorithm to find the frequent itemsets
freq_items=apriori(df=germany_pivoted_data_onehot, min_support=0.02,use_colnames=True)
freq_items

      support                                           itemsets
0    0.029851                       (3 HOOK HANGER MAGIC GARDEN)
1    0.033167               (3 PIECE SPACEBOY COOKIE CUTTER SET)
2    0.023217                    (36 PENCILS TUBE RED RETROSPOT)
3    0.021559                         (36 PENCILS TUBE WOODLAND)
4    0.029851                (5 HOOK HANGER RED MAGIC TOADSTOOL)
..        ...                                                ...
492  0.023217  (PLASTERS IN TIN WOODLAND ANIMALS, POSTAGE, PL...
493  0.029851  (PLASTERS IN TIN WOODLAND ANIMALS, POSTAGE, RO...
494  0.021559  (WOODLAND CHARLOTTE BAG, POSTAGE, RED RETROSPO...
495  0.026534  (POSTAGE, SPACEBOY LUNCH BOX , ROUND SNACK BOX...
496  0.026534  (WOODLAND CHARLOTTE BAG, POSTAGE, ROUND SNACK ...

[497 rows x 2 columns]

In [42]:
best_associates=association_rules(df=freq_items,metric='confidence',min_threshold=0.02,)
best_associates

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(POSTAGE),(3 PIECE SPACEBOY COOKIE CUTTER SET),0.635158,0.033167,0.026534,0.041775,1.259530,1.0,0.005467,1.008983,0.564773,0.041344,0.008903,0.420888
1,(3 PIECE SPACEBOY COOKIE CUTTER SET),(POSTAGE),0.033167,0.635158,0.026534,0.800000,1.259530,1.0,0.005467,1.824212,0.213122,0.041344,0.451818,0.420888
2,(POSTAGE),(5 HOOK HANGER RED MAGIC TOADSTOOL),0.635158,0.029851,0.021559,0.033943,1.137076,1.0,0.002599,1.004236,0.330420,0.033505,0.004218,0.378082
3,(5 HOOK HANGER RED MAGIC TOADSTOOL),(POSTAGE),0.029851,0.635158,0.021559,0.722222,1.137076,1.0,0.002599,1.313433,0.124260,0.033505,0.238636,0.378082
4,(POSTAGE),(6 RIBBONS RUSTIC CHARM),0.635158,0.082919,0.069652,0.109661,1.322507,1.0,0.016985,1.030036,0.668398,0.107417,0.029160,0.474830
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,"(ROUND SNACK BOXES SET OF 4 FRUITS , ROUND SNA...","(WOODLAND CHARLOTTE BAG, POSTAGE)",0.102819,0.087894,0.026534,0.258065,2.936093,1.0,0.017497,1.229360,0.734982,0.161616,0.186569,0.279976
1052,(WOODLAND CHARLOTTE BAG),"(POSTAGE, ROUND SNACK BOXES SET OF 4 FRUITS , ...",0.097844,0.094527,0.026534,0.271186,2.868867,1.0,0.017285,1.242393,0.722082,0.160000,0.195102,0.275944
1053,(POSTAGE),"(WOODLAND CHARLOTTE BAG, ROUND SNACK BOXES SET...",0.635158,0.029851,0.026534,0.041775,1.399478,1.0,0.007574,1.012445,0.782386,0.041558,0.012292,0.465332
1054,(ROUND SNACK BOXES SET OF 4 FRUITS ),"(WOODLAND CHARLOTTE BAG, POSTAGE, ROUND SNACK ...",0.129353,0.044776,0.026534,0.205128,4.581197,1.0,0.020742,1.201733,0.897857,0.179775,0.167869,0.398860
1055,(ROUND SNACK BOXES SET OF4 WOODLAND ),"(WOODLAND CHARLOTTE BAG, POSTAGE, ROUND SNACK ...",0.197347,0.031509,0.026534,0.134454,4.267138,1.0,0.020316,1.118936,0.953900,0.131148,0.106294,0.488280

In [43]:
best_associates.to_csv("best_anticidents_consequents_germany.csv")

## The End!